mode: restart
blueprint:
  name: Light Follow (Parent Child Light Control)
  author: leiflang
  source_url: https://raw.githubusercontent.com/leiflang/home-assistant-custom-code/refs/heads/main/blueprints/automations/LightFollow.yaml
  description: |
    # Light Follow (Parent Child Light Control)
    ## Version: 1.0.0
    This blueprint allows you to set a "Parent" light that the children light(s) will follow the state (on/off), brightness and colour/hue.
    Using the "Control Colour/Hue" toggle you can select if you want to control just the state and brightness or state, brightness and colour/hue.  
    If your parent light changes many times in short succesion befor landing on a final state, say the light dims down before turning off, you can set the Change Delay (Seconds) so only once the state settles for a set amount of time will it try to update the state of the child lights.

    ## Limitations
    If the parent light does not have brightness, colour and/or hue, then the this script will not be able to control those values for the children lights.
    There should not be any issues if the child light does not support all the features that the parent light supports, the applicable features will be controlled.
    If you want to have more then 1 light be a "Parent Light" you will need to create a helper in home assistant. 

    # Change Log
    ### Version 1.1.0
    Updated to allow checking both colour_temp and colour_temp_kelvin for lights that support just one but not the other
    ### Version 1.0.0
    Initial Version

    # Extra Info and Links
    [Copyright License](https://github.com/leiflang/home-assistant-custom-code/blob/main/LICENSE.txt)
    [GitHub](https://github.com/leiflang/home-assistant-custom-code/blob/main/blueprints/automations/LightFollow.yaml)

  domain: automation
  input:
    parent_light:
      name: Parent Light
      description: "This is the main light or parent light. All other lights will follow the state, colour temp and colour of this light"
      selector:
        entity:
          domain: light
    parent_control_colour:
      name: Control Colour/Hue
      description: |
        Enable to have the parent light control the state, brightness and colour/hue of the children lights.  
        Disable to only control child light state and brightness.
      selector:
        boolean: {}
      default: true
    child_light:
      name: Child Light
      description: "These are the children light(s), they will follow the state, colour temp and colour of the parent light"
      selector:
        entity:
          multiple: true
          domain: light
    change_delay_seconds:
      name: Change Delay (Seconds)
      description: "How long to wait after the parent has changed states to apply the changes to the child"
      default: 0
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: seconds
alias: Light Follow
description: ""
triggers:
  - trigger: state
    entity_id:
      - !input parent_light
    id: trigger
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: !input change_delay_seconds
      milliseconds: 1
  - variables:
      light_status: "{{trigger.to_state.state}}"
      light_brightness: "{{trigger.to_state.attributes.brightness | default(None)}}"
      light_hs_colour: "{{trigger.to_state.attributes.hs_color | default(None)}}"
      light_colour_temp: "{{trigger.to_state.attributes.color_temp | default(None)}}"
      light_colour_kelvin: "{{trigger.to_state.attributes.color_temp_kelvin | default(None)}}"
      control_colour: !input parent_control_colour
  - action: logbook.log
    metadata: {}
    data:
      name: Values
      message: |-
        Light Status: {{light_status}}
        Light Brightness: {{light_brightness}}
        Light Colour Hue/Saturation: {{light_hs_colour}}
        Light Colour Temp: {{light_colour_temp}}
        Light Colour Kelvin: {{light_colour_kelvin}}
  - repeat:
      for_each: !input child_light
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{light_status == 'on' and (light_colour_temp is none and light_hs_colour is none or control_colour == false)}}"
              sequence:
                - action: light.turn_on
                  metadata: {}
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness: "{{light_brightness}}"
              alias: When the light turns on but does not suppoer colour
            - conditions:
                - condition: template
                  value_template: "{{light_status == 'on' and light_colour_temp is not none}}"
              sequence:
                - action: light.turn_on
                  metadata: {}
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness: "{{light_brightness}}"
                    color_temp: "{{light_colour_temp}}"
              alias: When the light turns on or changes colour temp state
            - conditions:
                - condition: template
                  value_template: "{{light_status == 'on' and light_colour_kelvin is not none}}"
              sequence:
                - action: light.turn_on
                  metadata: {}
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness: "{{light_brightness}}"
                    color_temp_kelvin: "{{light_colour_kelvin}}"
              alias: When the light turns on or changes colour kelvin state
            - conditions:
                - condition: template
                  value_template: "{{light_status == 'on' and light_colour_temp is none}}"
              sequence:
                - action: light.turn_on
                  metadata: {}
                  target:
                    entity_id: "{{ repeat.item }}"
                  data:
                    brightness: "{{light_brightness}}"
                    hs_color: "{{light_hs_colour}}"
              alias: When the light turns on or changes colour state
            - conditions:
                - condition: template
                  value_template: "{{light_status == 'off'}}"
              sequence:
                - action: light.turn_off
                  metadata: {}
                  target:
                    entity_id: "{{ repeat.item }}"
                  data: {}
              alias: If light is turned off
